version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: master
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
